-- 코드를 입력하세요
# LEFT JOIN
SELECT
    CAR_ID, CAR_TYPE,
    TRUNCATE(DAILY_FEE * (100-DISCOUNT_RATE) * 0.01 * 30, 0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR
LEFT JOIN (
    SELECT * FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE IN ('세단', 'SUV') AND DURATION_TYPE = '30일 이상'
) AS t USING (CAR_TYPE)
WHERE
    (CAR_ID IN (
        SELECT CAR_ID FROM CAR_RENTAL_COMPANY_CAR
        WHERE CAR_ID NOT IN (
            SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        )
    )
    OR CAR_ID NOT IN (
        SELECT DISTINCT CAR_ID FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE END_DATE > '2022-11-01'    
    ))
    AND DAILY_FEE * (100-DISCOUNT_RATE) * 0.01 * 30 BETWEEN 500000 AND 2000000-1
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC;